src/winusb: Fix param. name typo
Signed-off-by: 林博仁 <Buo.Ren.Lin@gmail.com>

diff --git a/src/winusb b/src/winusb
--- a/src/winusb
+++ b/src/winusb
@@ -189,7 +189,7 @@ mount_source_and_target_filesystem(){
 
 	if [ "${needed_space}" -gt "${free_space}" ]; then
 		echo "Error: Not enough free space on '${partition}'!" >&2
-		echo "Error: We required ${neededspace} bytes but '${partition}' only has ${free_space} bytes." >&2
+		echo "Error: We required ${needed_space} bytes but '${partition}' only has ${free_space} bytes." >&2
 		exit 1
 	fi
 }; declare -fr mount_source_and_target_filesystem
