src/winusb: Re-order functions for better reading
Signed-off-by: 林博仁 <Buo.Ren.Lin@gmail.com>

diff --git a/src/winusb b/src/winusb
--- a/src/winusb
+++ b/src/winusb
@@ -332,22 +332,6 @@ hideNoErr(){
 	return "$RETURN"
 }
 
-print_help(){
-	echo "${RUNTIME_EXECUTABLE_NAME} usage" >&2
-	echo "Install a Windows ISO on an FAT partition and edit MBR of the device" >&2
-	echo "  ${RUNTIME_EXECUTABLE_NAME} --install <iso path> <partition>" >&2
-	echo "  Example: ${RUNTIME_EXECUTABLE_NAME} --install win7_amd64.iso /dev/sdd1" >&2
-	echo "" >&2
-	echo "Completely format a drive and install the ISO on it" >&2
-	echo "  ${RUNTIME_EXECUTABLE_NAME} --format <iso path> <device>" >&2
-	echo "  Example: ${RUNTIME_EXECUTABLE_NAME} --format win7_amd64.iso /dev/sdd" >&2
-	echo "" >&2
-	echo "Options" >&2
-	echo " --verbose, -v        Verbose mode" >&2
-	echo " --help, -h           Show this help message and exit" >&2
-	echo " --no_color            Disable color" >&2
-}; declare -fr print_help
-
 # Copy a file from A to B, overwrite file if B exists
 copy_file(){
 	source_file="$1" # A
@@ -422,28 +406,21 @@ copy_filesystem_files(){
 	done < <(echo "$file_list")
 }
 
-## Traps: Functions that are triggered when certain condition occurred
-## Shell Builtin Commands » Bourne Shell Builtins » trap
-trap_errexit(){
-	printf "An error occurred and the script is prematurely aborted\n" 1>&2
-	return 0
-}; declare -fr trap_errexit; trap trap_errexit ERR
-
-trap_exit(){
-	cleanup_mountpoints
-	return 0
-}; declare -fr trap_exit; trap trap_exit EXIT
-
-trap_return(){
-	local returning_function="${1}"
-
-	printf "DEBUG: %s: returning from %s\n" "${FUNCNAME[0]}" "${returning_function}" 1>&2
-}; declare -fr trap_return
-
-trap_interrupt(){
-	printf "Recieved SIGINT, script is interrupted.\n" 1>&2
-	return 0
-}; declare -fr trap_interrupt; trap trap_interrupt INT
+print_help(){
+	echo "${RUNTIME_EXECUTABLE_NAME} usage" >&2
+	echo "Install a Windows ISO on an FAT partition and edit MBR of the device" >&2
+	echo "  ${RUNTIME_EXECUTABLE_NAME} --install <iso path> <partition>" >&2
+	echo "  Example: ${RUNTIME_EXECUTABLE_NAME} --install win7_amd64.iso /dev/sdd1" >&2
+	echo "" >&2
+	echo "Completely format a drive and install the ISO on it" >&2
+	echo "  ${RUNTIME_EXECUTABLE_NAME} --format <iso path> <device>" >&2
+	echo "  Example: ${RUNTIME_EXECUTABLE_NAME} --format win7_amd64.iso /dev/sdd" >&2
+	echo "" >&2
+	echo "Options" >&2
+	echo " --verbose, -v        Verbose mode" >&2
+	echo " --help, -h           Show this help message and exit" >&2
+	echo " --no_color            Disable color" >&2
+}; declare -fr print_help
 
 process_commandline_parameters(){
 	if [ "${#RUNTIME_COMMANDLINE_PARAMETERS[@]}" -eq 0 ]; then
@@ -526,5 +503,28 @@ shift_array(){
 
 	return "${COMMON_RESULT_SUCCESS}"
 }; declare -fr shift_array
+
+## Traps: Functions that are triggered when certain condition occurred
+## Shell Builtin Commands » Bourne Shell Builtins » trap
+trap_errexit(){
+	printf "An error occurred and the script is prematurely aborted\n" 1>&2
+	return 0
+}; declare -fr trap_errexit; trap trap_errexit ERR
+
+trap_exit(){
+	cleanup_mountpoints
+	return 0
+}; declare -fr trap_exit; trap trap_exit EXIT
+
+trap_return(){
+	local returning_function="${1}"
+
+	printf "DEBUG: %s: returning from %s\n" "${FUNCNAME[0]}" "${returning_function}" 1>&2
+}; declare -fr trap_return
+
+trap_interrupt(){
+	printf "Recieved SIGINT, script is interrupted.\n" 1>&2
+	return 0
+}; declare -fr trap_interrupt; trap trap_interrupt INT
 
 init "${@}"
