src/winusb: Be more verbose on lacking space error condition
Signed-off-by: 林博仁 <Buo.Ren.Lin@gmail.com>

diff --git a/src/winusb b/src/winusb
--- a/src/winusb
+++ b/src/winusb
@@ -103,6 +103,7 @@ init(){
 
 	if [ "${needed_space}" -gt "${free_space}" ]; then
 		echo "Error: Not enough free space on '${partition}'!" >&2
+		echo "Error: We required ${neededspace} bytes but '${partition}' only has ${free_space} bytes." >&2
 		exit 1
 	fi
 
