src/winusb: pulse: Improve message
Signed-off-by: 林博仁 <Buo.Ren.Lin@gmail.com>

diff --git a/src/winusb b/src/winusb
--- a/src/winusb
+++ b/src/winusb
@@ -553,7 +553,7 @@ pulse(){
 			cd /; while true; do sleep 0.05; echo 'pulse'; done &
 			pulse_current_pid="$!"
 		elif [ "$1" != 'off' ]; then
-			echo "Pulse: bad argument" >&2
+			echo "${FUNCNAME[0]}: Error: Illegal function parameter" >&2
 			exit 1
 		fi
 	fi
