src/winusb: Improve message wording
Signed-off-by: 林博仁 <Buo.Ren.Lin@gmail.com>

diff --git a/src/winusb b/src/winusb
--- a/src/winusb
+++ b/src/winusb
@@ -235,7 +235,7 @@ check_runtime_parameters(){
 
 	if [ ! -f "${source_media}" ] \
 		&& [ ! -b "${source_media}" ]; then
-		echo "Error: iso '${source_media}' not found or not a regular file or a block file!" >&2
+		echo "Error: source media '${source_media}' not found or not a regular file or a block device!" >&2
 		result="1"
 	fi
 
